import {useState,useEffect,useRef} from 'react';
import {Input} from '../components/ui';
import {MappedInput,CodeEditor} from './Editors';
export function ApiRows({label,values,onChange}:{label:string;values:Record<string,any>;onChange:(v:Record<string,any>,error?:string)=>void}){
 const [rows,setRows]=useState(()=>Object.entries(values));const [error,setError]=useState('');const last=useRef(JSON.stringify(values));
 useEffect(()=>{const next=JSON.stringify(values);if(next!==last.current){last.current=next;setRows(Object.entries(values));setError('')}},[values]);
 const save=(next:Array<[string,any]>)=>{setRows(next);const keys=next.filter(([k,v])=>k||v).map(([k])=>k);const problem=keys.some(k=>!k.trim())?'Enter a key for each value.':new Set(keys).size!==keys.length?'Each key must be unique.':'';setError(problem);last.current=JSON.stringify(Object.fromEntries(next.filter(([k])=>k)));onChange(JSON.parse(last.current),problem)};
 return <div className="space-y-3">{rows.map(([key,value],i)=><div key={i} className="grid grid-cols-[minmax(75px,1fr)_minmax(120px,2fr)_28px] items-start gap-2"><Input aria-label={label+' key '+(i+1)} placeholder="Key" value={key} onChange={e=>save(rows.map((r,n)=>n===i?[e.target.value,r[1]]:r))}/><MappedInput label={label+' value '+(i+1)} value={value?.$ref?'{{'+value.$ref+'}}':typeof value==='object'?JSON.stringify(value):String(value??'')} onChange={value=>save(rows.map((r,n)=>n===i?[r[0],value]:r))}/><button type="button" aria-label={'Remove '+label+' '+(i+1)} className="mt-2 text-neutral-400 hover:text-red-400" onClick={()=>save(rows.filter((_,n)=>n!==i))}><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8"><path d="M3 6h18M9 6V3h6v3M5 6l1 15h12l1-15M10 10v7M14 10v7"/></svg></button></div>)}<button type="button" className="text-sm text-accent hover:underline" onClick={()=>setRows([...rows,['','']])}>⊕ Add another item</button>{error&&<p role="alert" className="text-xs text-red-400">{error}</p>}</div>
}
export function ApiBody({config,onChange}:{config:Record<string,any>;onChange:(v:Record<string,any>)=>void}){
 const contentType=config.contentType??'application/json';const json=contentType==='application/json';const value=config.bodyDraft??(json?JSON.stringify(config.body??{},null,2):String(config.body??''));
 if(contentType==='application/x-www-form-urlencoded'&&!config.body?.$ref)return <ApiRows key={contentType} label="Form field" values={config.body??{}} onChange={(body,bodyError)=>onChange({body,bodyError,bodyDraft:undefined})}/>;
 return <><CodeEditor label="Raw body" language={json?'json':contentType==='application/xml'?'html':'text'} value={value} onChange={text=>{if(!json){onChange({body:text,bodyDraft:undefined,bodyError:undefined});return}try{onChange({body:JSON.parse(text),bodyDraft:text,bodyError:undefined})}catch{onChange({bodyDraft:text,bodyError:'Correct the JSON body before running this action.'})}}}/>{config.bodyError&&<p role="alert" className="text-xs text-red-400">{config.bodyError}</p>}</>
}
