import {useRef,useState,type ReactNode} from 'react';
import {SearchSelect} from './SearchSelect';
import {useFieldSources} from './FieldSources';
import {Button} from '../components/ui';

export function MappedInput({label,value,onChange,multiline=false,secret=false}:{label:string;value:string;onChange:(v:string)=>void;multiline?:boolean;secret?:boolean}){
 const ref=useRef<HTMLInputElement & HTMLTextAreaElement>(null);const [open,setOpen]=useState(false);const sources=useFieldSources();
 const props={ref,'aria-label':label,value,onChange:(e:React.ChangeEvent<HTMLInputElement|HTMLTextAreaElement>)=>onChange(e.target.value),className:'w-full min-w-0 rounded-md border border-edge bg-ink px-3 py-2 pr-10 text-sm text-white focus:outline-accent'};
 return <div className="space-y-2"><div className="relative">{multiline?<textarea {...props} rows={5}/>:<input {...props} type={secret?'password':'text'}/>}<button type="button" aria-label={'Custom values for '+label} title="Custom values" className="absolute right-1 top-1 flex h-8 w-8 items-center justify-center rounded text-neutral-400 hover:bg-raised hover:text-accent" onClick={()=>setOpen(!open)}><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8"><path d="M3 3h7l11 11-7 7L3 10z"/><circle cx="7.5" cy="7.5" r="1"/></svg></button></div>{open&&<SearchSelect label={'Choose custom value for '+label} value="" placeholder="Choose a custom value…" options={sources.map(s=>({value:s.path,label:s.label,detail:s.group}))} onChange={path=>{const start=ref.current?.selectionStart??value.length;const end=ref.current?.selectionEnd??start;const token='{{'+path+'}}';onChange(value.slice(0,start)+token+value.slice(end));setOpen(false);requestAnimationFrame(()=>{ref.current?.focus();ref.current?.setSelectionRange(start+token.length,start+token.length)})}}/>}</div>
}

export function CodeEditor({label,value,onChange,language='javascript'}:{label:string;value:string;onChange:(v:string)=>void;language?:'javascript'|'json'|'html'|'text'}){
 const editor=useRef<HTMLTextAreaElement>(null);const gutter=useRef<HTMLPreElement>(null);const highlight=useRef<HTMLPreElement>(null);const latest=useRef(value);latest.current=value;const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [fields,setFields]=useState(false);const sources=useFieldSources();
 const insert=(text:string)=>{const start=editor.current?.selectionStart??value.length;const end=editor.current?.selectionEnd??start;onChange(value.slice(0,start)+text+value.slice(end));requestAnimationFrame(()=>{editor.current?.focus();editor.current?.setSelectionRange(start+text.length,start+text.length)})};
 const format=async()=>{setBusy(true);setError('');const original=value;try{const [{format},babel,estree,html]=await Promise.all([import('prettier/standalone'),import('prettier/plugins/babel'),import('prettier/plugins/estree'),import('prettier/plugins/html')]);const formatted=await format(original,{parser:language==='javascript'?'babel':language==='json'?'json':'html',plugins:[babel.default,estree.default,html.default],tabWidth:2,printWidth:80});if(latest.current===original)onChange(formatted)}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 return <div className="space-y-2"><div className="flex items-center justify-between"><span className="text-sm font-medium text-white">{label}</span><div className="flex gap-2"><Button onClick={()=>setFields(!fields)}>Custom values</Button>{language!=='text'&&<Button disabled={busy} onClick={format}>{busy?'Formatting…':'Format code'}</Button>}</div></div>{language==='html'&&<div className="flex flex-wrap gap-2">{[['Bold','strong'],['Italic','em'],['Heading','h2'],['Paragraph','p'],['List','ul']].map(([title,tag])=><Button key={tag} onClick={()=>{const selected=value.slice(editor.current?.selectionStart??0,editor.current?.selectionEnd??0)||'Text';insert('<'+tag+'>'+(tag==='ul'?'<li>'+selected+'</li>':selected)+'</'+tag+'>')}}>{title}</Button>)}</div>}{fields&&<SearchSelect label={'Custom values for '+label} value="" placeholder="Choose a field…" options={sources.map(s=>({value:s.path,label:s.label,detail:s.group}))} onChange={path=>{insert(language==='javascript'?path.replace(/^trigger/,'input'):'{{'+path+'}}');setFields(false)}}/>}<div className="flex overflow-hidden rounded-md border border-edge bg-ink focus-within:border-accent"><pre ref={gutter} aria-hidden="true" className="m-0 max-h-80 select-none overflow-hidden border-r border-edge bg-panel px-2 py-3 text-right font-mono text-xs leading-5 text-neutral-500">{value.split('\n').map((_,i)=>i+1).join('\n')}</pre><div className="relative min-w-0 flex-1"><pre ref={highlight} aria-hidden="true" className="pointer-events-none absolute inset-0 m-0 overflow-hidden whitespace-pre p-3 font-mono text-xs leading-5 text-white">{highlightCode(value)}{'\n'}</pre><textarea ref={editor} aria-label={label} spellCheck={false} wrap="off" value={value} style={{color:'transparent',WebkitTextFillColor:'transparent'}} className="relative block min-h-64 max-h-80 w-full min-w-0 resize-y bg-transparent p-3 font-mono text-xs leading-5 caret-black focus:outline-none" onScroll={()=>{if(gutter.current&&editor.current)gutter.current.scrollTop=editor.current.scrollTop;if(highlight.current&&editor.current){highlight.current.scrollTop=editor.current.scrollTop;highlight.current.scrollLeft=editor.current.scrollLeft}}} onChange={e=>{setError('');onChange(e.target.value)}} onKeyDown={e=>{if(e.key==='Tab'&&!e.shiftKey){e.preventDefault();insert('  ')}if(e.key==='Enter'){e.preventDefault();const before=value.slice(0,e.currentTarget.selectionStart);const indent=before.split('\n').at(-1)?.match(/^\s*/)?.[0]??'';insert('\n'+indent+(/[\[{]\s*$/.test(before)?'  ':''))}if(e.altKey&&e.shiftKey&&e.key.toLowerCase()==='f'){e.preventDefault();void format()}}}/></div></div>{error&&<pre role="alert" className="whitespace-pre-wrap text-xs text-red-400">{error}</pre>}</div>
}

function highlightCode(code:string):ReactNode[]{
 const pattern=/(\/\*[\s\S]*?\*\/|\/\/[^\n]*|"(?:\\.|[^"\\])*"|'(?:\\.|[^'\\])*'|`(?:\\.|[^`\\])*`|\b(?:const|let|var|return|await|async|function|if|else|for|of|throw|new|try|catch|true|false|null|undefined)\b|\b\d+(?:\.\d+)?\b)/g;
 const parts:ReactNode[]=[];let end=0;
 for(const match of code.matchAll(pattern)){const at=match.index!;if(at>end)parts.push(code.slice(end,at));const token=match[0];const color=token.startsWith('/')?'#a34800':/^["'`]/.test(token)?'#187342':/^\d/.test(token)?'#1558d6':'#7523bb';parts.push(<span key={at} style={{color}}>{token}</span>);end=at+token.length}
 parts.push(code.slice(end));return parts;
}
