import {useEffect,useId,useRef,useState} from 'react';
export type SearchOption={value:string;label:string;detail?:string};
export function SearchSelect({label,value,onChange,options,placeholder='Choose…'}:{label:string;value:string;onChange:(v:string)=>void;options:SearchOption[];placeholder?:string}){
 const [open,setOpen]=useState(false);const [query,setQuery]=useState('');const [active,setActive]=useState(0);const root=useRef<HTMLDivElement>(null);const input=useRef<HTMLInputElement>(null);const id=useId();
 const filtered=options.filter(o=>(o.label+' '+o.detail+' '+o.value).toLowerCase().includes(query.toLowerCase()));
 useEffect(()=>{if(open)input.current?.focus();const close=(e:PointerEvent)=>{if(!root.current?.contains(e.target as Node))setOpen(false)};document.addEventListener('pointerdown',close);return()=>document.removeEventListener('pointerdown',close)},[open]);
 const choose=(v:string)=>{onChange(v);setOpen(false);root.current?.querySelector('button')?.focus()};
 return <div ref={root} className="relative min-w-0"><button type="button" aria-label={label} aria-haspopup="listbox" aria-expanded={open} onClick={()=>{setOpen(!open);setQuery('');setActive(0)}} className="flex w-full items-center justify-between gap-3 rounded-md border border-edge bg-ink px-3 py-2 text-left text-sm text-white hover:border-accent focus-visible:outline-2 focus-visible:outline-accent"><span className="truncate">{options.find(o=>o.value===value)?.label||value||placeholder}</span><span aria-hidden="true">⌄</span></button>{open&&<div className="absolute left-0 right-0 top-full z-50 mt-1 overflow-hidden rounded-md border border-edge bg-panel shadow-lg"><input ref={input} role="combobox" aria-label={'Search '+label} aria-expanded="true" aria-controls={id} aria-activedescendant={filtered[active]?id+'-'+active:undefined} value={query} placeholder="Search by name or module…" onChange={e=>{setQuery(e.target.value);setActive(0)}} onKeyDown={e=>{if(e.key==='Escape'){setOpen(false);root.current?.querySelector('button')?.focus()}if(e.key==='ArrowDown'){e.preventDefault();setActive(Math.min(active+1,filtered.length-1))}if(e.key==='ArrowUp'){e.preventDefault();setActive(Math.max(0,active-1))}if(e.key==='Enter'&&filtered[active]){e.preventDefault();choose(filtered[active].value)}}} className="w-full border-b border-edge bg-ink px-3 py-2.5 text-sm text-white outline-none"/><div id={id} role="listbox" aria-label={label} className="max-h-64 overflow-y-auto">{filtered.map((o,i)=><button key={o.value+' '+o.detail} id={id+'-'+i} ref={node=>{if(node&&i===active)node.scrollIntoView({block:'nearest'})}} role="option" aria-selected={o.value===value} type="button" onMouseEnter={()=>setActive(i)} onClick={()=>choose(o.value)} className={'flex w-full items-center justify-between gap-2 px-3 py-2 text-left text-sm '+(i===active?'bg-raised text-white':'text-neutral-300 hover:bg-raised')}><span>{o.label}{o.detail&&<span className="block text-xs text-neutral-500">{o.detail}</span>}</span>{o.value===value&&<span aria-hidden="true">✓</span>}</button>)}{!filtered.length&&<p className="p-3 text-sm text-neutral-500">No matches. Try a different name.</p>}</div><div className="border-t border-edge px-3 py-2 text-xs text-neutral-500">{filtered.length} results</div></div>}</div>
}
