import {useEffect,useState} from 'react';
import {useParams} from 'react-router-dom';
import {Button,Input} from '../components/ui';
import {request} from './api';
export function WebhookCapture({triggerId}:{triggerId?:string}){
 const {workflowId}=useParams();const [hook,setHook]=useState<any>();const [capture,setCapture]=useState<any>();const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 const base=`workflows/${workflowId}`;
 useEffect(()=>{let alive=true;if(!workflowId||!triggerId)return;request(`${base}/webhook?triggerId=${encodeURIComponent(triggerId)}`).then(h=>{if(alive)setHook(h)}).catch(e=>{if(alive)setError(e.message)});const load=()=>request(`${base}/webhook-sample?triggerId=${encodeURIComponent(triggerId)}`).then(s=>{if(alive){setCapture(s);if(s.sample){sessionStorage.setItem('automation-test-input',JSON.stringify(s.sample));window.dispatchEvent(new CustomEvent('webhook-sample',{detail:{triggerId,sample:s.sample}}))}}}).catch(e=>{if(alive)setError(e.message)});load();const timer=setInterval(load,2000);return()=>{alive=false;clearInterval(timer)}},[workflowId,triggerId]);
 if(!workflowId||!triggerId)return <p className="text-xs text-neutral-500">Save the workflow to generate this webhook’s URL.</p>;
 return <div className="space-y-3 border-t border-edge pt-4"><h3 className="text-sm font-medium text-white">Webhook URL</h3>{hook&&<><Input aria-label="Production webhook URL" readOnly value={hook.url}/><Button onClick={()=>navigator.clipboard.writeText(hook.url)}>Copy URL</Button><p className="text-xs text-neutral-500">Use this URL when the workflow is published. Authenticate with the webhook secret.</p><Button onClick={()=>navigator.clipboard.writeText(hook.secret)}>Copy webhook secret</Button><h3 className="text-sm font-medium text-white">Capture a test event</h3><Input aria-label="Test webhook URL" readOnly value={hook.testUrl}/><div className="flex flex-wrap gap-2"><Button onClick={()=>navigator.clipboard.writeText(hook.testUrl)}>Copy test URL</Button><Button onClick={()=>navigator.clipboard.writeText(hook.testSecret)}>Copy test secret</Button></div><p className="text-xs text-neutral-500">Send JSON with {hook.authentication?.startsWith('X-Automation-Secret')?'X-Automation-Secret: followed by the test secret.':'Authorization: Bearer followed by the test secret.'} This captures fields without running actions.{!hook.publicUrlConfigured?' This local URL works on this computer; external apps need a public HTTPS address configured.':''}</p><Button disabled={busy||capture?.listening} onClick={async()=>{setBusy(true);setError('');try{setCapture(await request(`${base}/listen`,'POST',{triggerId}))}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}>{capture?.listening?'Waiting for a test event…':'Listen for test event'}</Button>{capture?.listening&&<p role="status" className="text-xs text-neutral-500">Listening for 5 minutes.</p>}{capture?.sample&&<><p role="status" className="text-sm text-white">Test event received. Its fields are available in the data picker.</p><details><summary className="cursor-pointer text-xs text-neutral-400">View captured payload</summary><pre className="max-h-48 overflow-auto text-xs">{JSON.stringify(capture.sample,null,2)}</pre></details></>}</>}{error&&<p role="alert" className="text-xs text-red-400">{error} Save any new trigger before capturing a test event.</p>}</div>
}
